services:
    appbundle_form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - appbundle_game_form
            - appbundle_game_form
            - null
    #Game Form
    appbundle_game_form:
        class: AppBundle\Form\Type\GameMatchType
        arguments:
            - @move.provider
        tags:
            - { name: form.type, alias: appbundle_game_form }