services:
    form.update_handler:
        class: AppBundle\Form\Handler\UpdateHandler
        arguments:
            - @doctrine.orm.entity_manager
            - @request_stack
            - @templating
            - @router

    move.provider:
        class: AppBundle\Provider\MoveProvider

    result.provider:
        class: AppBundle\Provider\ResultProvider

    ae_business.event_listener:
        class:  AppBundle\Event\GameMatchListener
        arguments:
            - @result.provider
        tags:
            - { name: doctrine.event_listener, event: prePersist }